### ISSUE TITLE
Is it possible to use this package to "transform" xml into (X)HTML? 

### ISSUE THREAD

**Issue by JonathanReeve** [ymtszw/elm-xml-decode#7]
I have some files that are in TEI XML, which has a lot of overlap with HTML, but needs some changes in order to be displayed. The files can be rather complicated. Is it possible to use this package and somehow declare a list of things to  transform? That would, say, leave all the `<p>` tags alone, but would be able to take `<said who="Joe">Hiya Phil</said>` and transform it into `<span class="quotation" data-attribution="Joe">Hiya Phil</span>`? But then keep everything else about the same?

**Comment by ymtszw** [comment]
In theory it should be possible, however in order to do that you have to write complete "TEI XML => XHTML" node mapping function.
Since `Xml.Decode` only provides elementary functions to transform Xml nodes into Elm values, and does not come with XHTML knowledge at all.

Also, we need to know your targeted data structure precisely.

- Do you want to transform your data into whole `Html.Html msg` (i.e. `VirtualDom.Node msg`) and display them as an Elm view,
- OR, you actualy want to serialize them into complete XHTML-formatted text (i.e. `String`) and pass it over somewhere?

The former should be straightforward. You just need to write (albeit somewhat complicated and large) `Xml.Decode.Decoder (Html.Html msg)` using functions from `Xml.Decode` and `Html` modules.

The latter is a bit problematic since this package does not come with `Xml.Encode` (like in `Json.Encode`). Meaning, there is currently no supported way of transforming (serializing) Elm values into another complete Xml documents.

**Comment by JonathanReeve** [comment]
Awesome. It's the first: I'm just thinking about ways to transform XML to Html using Elm. 

Is there a way to walk an XML tree, transforming any node along the way? That's the thing I'm having difficulty imagining how to do. For some nodes, I know what they look like (e.g. a `<span>` somewhere), but not where they are in the hierarchy, so I can't select them with a path.

**Comment by ymtszw** [comment]
Acutally, after some thought I had found it does not require this particular package, since the essential part is walking through XML tree and transforming any node along the way, right?
`XmlParser` (on which this package relies) is the basic component to construct XML trees from raw XML documents. And you can just walk through them with plain recursive functions.

Check out type definitions on `XmlParser` here: https://package.elm-lang.org/packages/jinjor/elm-xml-parser/latest/XmlParser

Quick and not-tested example:

```elm
import Html exposing (..)
import Html.Attributes exposing (..)
import XmlParser exposing (Node(..))

{- Example:

<said who="Joe">Hiya Phil</said>
--> Element "said" [ { name = "who", value = "Joe" } ] [ Text "Hiya Phil" ]

-}
walkTEI : List (Html msg) -> List Node -> List (Html msg)
walkTEI acc node =
    case node of
        [] ->
            List.reverse acc

        Text str :: xs ->
            walkTEI (text str :: acc) xs

        Element nodeName attrs kids :: xs ->
            let
                -- Depth-first walk
                transformedKids =
                    walkTEI [] kids
            in
            walkTEI (mapTEINodeToXHTML nodeName attrs transformedKids :: acc) xs


mapTEINodeToXHTML : String -> List XmlParser.Attribute -> List (Html msg) -> Html msg
mapTEINodeToXHTML nodeName attrs transformedKids =
    case nodeName of
        "said" ->
            span
                [ class "quotation"
                , mapAttributeWithFallback "who" "data-attribution" attrs
                ]
                transformedKids

        -- branches for other possibilities should follow

        xhtmlCompatibleNodeName ->
            let
                transformedAttrs =
                    List.map (\{ name, value } -> attribute name value) attrs
            in
            node xhtmlCompatibleNodeName transformedAttrs transformedKids


mapAttributeWithFallback : String -> String -> List (Attribute msg) -> Attribute msg
mapAttributeWithFallback nameFrom nameTo attrs =
    getAttributeByName nameFrom attrs
        |> Maybe.map (attribute nameTo)
        |> Maybe.withDefault noAttr


getAttributeByName : String -> List (Attribute msg) -> Maybe String
getAttributeByName name_ attrs =
    case attrs of
        [] ->
            Nothing

        { name, value } :: xs ->
            if name == name_ then
                Just value

            else
                getAttributeByName name_ xs


noAttr : Attribute msg
noAttr =
    class ""
```

Hope it delivers.

**Comment by ymtszw** [comment]
Closing for now. Feel free to post any further questions. @JonathanReeve

**Comment by JonathanReeve** [comment]
Thanks so much for this code! I'll give it a try.
